import { Publication } from "@/types/publication";

const PublicationData: Publication[] = [
  {
    _id: 1,
    category: "Archives",
    title: "Les Cahiers du CAHDIIP n° 4",
    pdfUrl: "/pdf/Les Cahiers du CAHDIIP n° 4.pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "Les Cahiers du CAHDIIP n° 4.",
  },
  {
    _id: 2,
    category: "Archives",
    title: "Les Cahiers du CAHDIIP n° 5",
    pdfUrl: "/pdf/Les Cahiers du CAHDIIP n°5.pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "Les Cahiers du CAHDIIP n° 5.",
  },
  {
    _id: 3,
    category: "Archives",
    title: "NBBS Revue Les cahiers du cahdiip N°3",
    pdfUrl: "/pdf/NBBS Revue Les cahiers du cahdiip N°3 (2) (1).pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "NBBS Revue Les cahiers du cahdiip N°3.",
  },
  {
    _id: 4,
    category: "Archives",
    title: "Numero 1 REVUE CAHDIIP",
    pdfUrl: "/pdf/numero 1 REVUE CAHDIIP (3) (1) (1).pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "Numero 1 REVUE CAHDIIP.",
  },
  {
    _id: 5,
    category: "Les cahiers du cahdiip",
    title: "Les Cahiers du CAHDIIP 8 et 9",
    pdfUrl: "/pdf/Les Cahiers du CAHDIIP 8 et 9.pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "Les Cahiers du CAHDIIP 8 et 9.",
  },
  {
    _id: 6,
    category: "Les cahiers du cahdiip",
    title: "Soumettre un article à la revue LES CAHIERS DU CAHDIIP",
    pdfUrl:
      "/pdf/Soumettre un article à la revue LES CAHIERS DU CAHDIIP (2).pdf",
    thumbnail: "/images/pdf-thumbnail-04.png",
    metadata: "Soumettre un article à la revue LES CAHIERS DU CAHDIIP.",
  },
  {
    _id: 7,
    category: "Archives",
    title: "Les troisièmes journées du cahdiip",
    pdfUrl: "/pdf/Les troisièmes journées du cahdiip.pdf",
    thumbnail: "/images/pdf-thumbnail-02.png",
    metadata: "Les troisièmes journées du cahdiip.",
  },
  {
    _id: 8,
    category: "Archives",
    title: "THESE MME. AOULE EPOUSE CISSE_PAGE DE GARDE",
    pdfUrl: "/pdf/THESE MME. AOULE EPOUSE CISSE_PAGE DE GARDE.pdf",
    thumbnail: "/images/test.png",
    metadata: "THESE MME. AOULE EPOUSE CISSE_PAGE DE GARDE.",
  },
  {
    _id: 9,
    category: "Les cahiers du cahdiip",
    title: "Mot du directeur de la revue",
    pdfUrl: "/pdf/Mot du directeur de la revue.pdf",
    thumbnail: "/images/pdf-thumbnail-03.png",
    metadata: "Mot du directeur de la revue.",
  },
  {
    _id: 10,
    category: "Archives",
    title: "REVUE CAHDIIP NUMERO SPECIAL Janvier 2021",
    pdfUrl: "/pdf/REVUE CAHDIIP NUMERO SPECIAL Janvier 2021 (1) (1) (1).pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "REVUE CAHDIIP NUMERO SPECIAL Janvier 2021.",
  },
  {
    _id: 11,
    category: "Ouvrages",
    title: "ETAT CIVIL GOUVERNANCE PUBLIQUE Colloque international",
    pdfUrl:
      "/pdf/ETAT CIVIL GOUVERNANCE PUBLIQUE Colloque international (1).pdf",
    thumbnail: "/images/pdf-ouvrages-01.png",
    metadata: "ETAT CIVIL GOUVERNANCE PUBLIQUE Colloque international.",
  },
  {
    _id: 12,
    category: "Ouvrages",
    title: "Sorcellerie, pratiques et criminalisation",
    pdfUrl: "/pdf/Sorcellerie, pratiques et criminalisation  (24X2024) (3).pdf",
    thumbnail: "/images/pdf-ouvrages-02.png",
    metadata: "Sorcellerie, pratiques et criminalisation.",
  },
  {
    _id: 13,
    category: "Ouvrages",
    title: "MELANGES LEGRE",
    pdfUrl: "/pdf/MELANGES LEGRE (2).pdf",
    thumbnail: "/images/pdf-ouvrages-03.png",
    metadata: "MELANGES LEGRE.",
  },
  {
    _id: 14,
    category: "Ouvrages",
    title: "ACTES DU COLLOQUE FONCIER ET POUVOIR POLITIQUE",
    pdfUrl: "/pdf/ACTES DU COLLOQUE FONCIER ET POUVOIR POLITIQUE.pdf",
    thumbnail: "/images/pdf-ouvrages-04.png",
    metadata: "ACTES DU COLLOQUE FONCIER ET POUVOIR POLITIQUE.",
  },
  {
    _id: 15,
    category: "Archives",
    title: "Les Cahiers du CAHDIIP numéro VII",
    pdfUrl: "/pdf/Les Cahiers du CAHDIIP numéro VII.pdf",
    thumbnail: "/images/pdf-thumbnail-01.png",
    metadata: "Les Cahiers du CAHDIIP numéro VII.",
  },
];

export default PublicationData;
